import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Examples",
  description: "Sample narratives and assets generated by Go-to-Market Taste.",
};

const examples = [
  {
    company: "Acme RevOps Platform",
    category: "Revenue Operations",
    description:
      "A RevOps automation tool that syncs CRM, billing, and support data in real time. Sold to VP RevOps at mid-market B2B SaaS ($10M to $100M ARR).",
    tags: ["MEDDIC", "Pitch deck", "One-pager"],
    narrative: [
      {
        label: "Identify Pain",
        text: "RevOps teams spend 4 to 6 hours per week manually reconciling data across Salesforce, Stripe, and Zendesk. Reporting delays cause forecast inaccuracies of 15 to 20 percent.",
        badge: "verified",
      },
      {
        label: "Economic Buyer",
        text: "VP of Revenue Operations at companies with 50 to 500 employees. Secondary sign-off from CFO when contract exceeds $50k annually.",
        badge: "inferred",
      },
      {
        label: "Positive Business Outcome",
        text: "Finance closes books 3 days faster. Sales leadership trusts pipeline numbers. RevOps team redirects 20 hours per month from data wrangling to analysis.",
        badge: "verified",
      },
    ],
  },
  {
    company: "Focal AI",
    category: "Engineering Productivity",
    description:
      "An AI layer on Jira that flags specification gaps before a sprint starts. Sold to Heads of Engineering and CPOs at Series A to C product teams.",
    tags: ["Command of the Message", "Sales deck", "One-pager"],
    narrative: [
      {
        label: "Current State",
        text: "Engineering teams at Series A to C companies start sprints with incomplete or ambiguous specs 60 to 70 percent of the time. Mid-sprint clarifications add an average of 2 to 3 days of delay.",
        badge: "verified",
      },
      {
        label: "Required Capabilities",
        text: "Must integrate with Jira without requiring a new workflow. Must surface gaps before sprint planning, not during. Must be usable by PMs without engineering configuration.",
        badge: "verified",
      },
      {
        label: "Differentiated Value",
        text: "Unlike linting tools or PM checklists, Focal AI reads the actual ticket context and flags gaps based on what is missing, not what violates a rule. No rule configuration required.",
        badge: "inferred",
      },
    ],
  },
  {
    company: "HireLoop",
    category: "Talent Acquisition Infrastructure",
    description:
      "A structured hiring workflow platform for Series A to C companies scaling from 50 to 300 employees. Sold to VPs of People and COOs.",
    tags: ["MEDDIC", "Pitch deck", "Sales deck"],
    narrative: [
      {
        label: "Identify Pain",
        text: "Fast-growing teams at this stage hire across 8 to 15 roles simultaneously using a patchwork of spreadsheets, email, and a basic ATS. Candidates drop out or reject offers at a 35 percent higher rate than companies with a structured process.",
        badge: "verified",
      },
      {
        label: "Champion",
        text: "The VP of People or Head of Talent. Motivated by reducing time-to-hire and eliminating firefighting. Gains credibility with founders and the board by showing hiring velocity improvements.",
        badge: "inferred",
      },
      {
        label: "Metrics",
        text: "Customers report 40 percent reduction in time-to-offer, 25 percent improvement in offer acceptance rate, and 10 hours per week saved in coordination across hiring managers.",
        badge: "verified",
      },
    ],
  },
];

export default function ExamplesPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6">

      {/* Header */}
      <div className="mb-12 text-center">
        <Badge variant="secondary" className="mb-4">Examples</Badge>
        <h1 className="text-3xl font-bold tracking-tight">What the output looks like</h1>
        <p className="mt-3 text-muted-foreground max-w-xl mx-auto">
          Three sample projects showing what Go-to-Market Taste produces from a real B2B SaaS intake.
          Each excerpt below comes from Stage 2 of the pipeline: the core narrative.
        </p>
      </div>

      {/* Example cards */}
      <div className="space-y-10">
        {examples.map((ex) => (
          <div key={ex.company} className="rounded-lg border border-border bg-background">
            <div className="border-b border-border px-6 py-5">
              <div className="mb-2 flex flex-wrap items-center gap-2">
                <Badge variant="secondary">{ex.category}</Badge>
                {ex.tags.map((tag) => (
                  <Badge key={tag} variant="outline">{tag}</Badge>
                ))}
              </div>
              <h2 className="text-lg font-semibold text-foreground">{ex.company}</h2>
              <p className="mt-1 text-sm text-muted-foreground">{ex.description}</p>
            </div>
            <div className="p-6">
              <p className="label-xs mb-4">Core narrative excerpt</p>
              <div className="space-y-3">
                {ex.narrative.map((item) => (
                  <div key={item.label} className="rounded-md border border-border p-4">
                    <div className="mb-2 flex items-center justify-between">
                      <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                        {item.label}
                      </span>
                      <span
                        className={`inline-flex items-center rounded-full px-1.5 py-0.5 text-2xs font-medium ring-1 ring-inset ${
                          item.badge === "verified"
                            ? "bg-emerald-50 text-emerald-700 ring-emerald-200"
                            : "bg-amber-50 text-amber-700 ring-amber-200"
                        }`}
                      >
                        {item.badge}
                      </span>
                    </div>
                    <p className="text-sm leading-relaxed text-foreground">{item.text}</p>
                  </div>
                ))}
              </div>
              <p className="mt-4 text-xs text-muted-foreground">
                Full asset previews (pitch deck, one-pager, sales enablement deck) available inside the app.
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* CTA */}
      <div className="mt-12 rounded-lg border border-border bg-muted/30 p-8 text-center">
        <h2 className="mb-2 text-lg font-semibold">Ready to generate yours?</h2>
        <p className="mb-6 text-sm text-muted-foreground">
          Create a free account and fill in four fields. Your core narrative is ready in minutes.
        </p>
        <div className="flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
          <Button asChild>
            <Link href="/signup">
              Create account
              <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
          <Button variant="outline" asChild>
            <Link href="/product">See how it works</Link>
          </Button>
        </div>
      </div>

    </div>
  );
}
