import type { Metadata } from "next";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Examples",
  description: "Sample narratives and assets generated by NarrativeKit.",
};

const examples = [
  {
    company: "Acme RevOps Platform",
    category: "Revenue Operations",
    description:
      "A RevOps automation tool that syncs CRM, billing, and support data. Buyer is VP RevOps at mid-market SaaS.",
    tags: ["MEDDIC", "Pitch deck", "One-pager"],
  },
  {
    company: "Focal AI",
    category: "AI-assisted QA",
    description:
      "An AI layer on top of Jira that flags spec gaps before sprint. Buyer is Head of Engineering or CPO.",
    tags: ["Command of Message", "Sales deck", "One-pager"],
  },
  {
    company: "HireLoop",
    category: "Recruiting Infrastructure",
    description:
      "A structured hiring workflow platform for Series A–C teams scaling from 50 to 300 employees.",
    tags: ["MEDDIC", "Pitch deck", "Sales deck"],
  },
];

export default function ExamplesPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6">
      <div className="mb-12 text-center">
        <Badge variant="secondary" className="mb-4">Examples</Badge>
        <h1 className="text-3xl font-bold tracking-tight">See it in action</h1>
        <p className="mt-3 text-muted-foreground">
          Sample projects showing canonical narratives and generated assets.
          Full examples coming soon.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {examples.map((ex) => (
          <Card key={ex.company} hover>
            <CardHeader>
              <p className="label-xs mb-1">{ex.category}</p>
              <CardTitle>{ex.company}</CardTitle>
              <CardDescription>{ex.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-1.5">
                {ex.tags.map((tag) => (
                  <Badge key={tag} variant="secondary">{tag}</Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="mt-12 rounded-lg border border-dashed border-border bg-muted/30 p-8 text-center">
        <p className="text-sm font-medium text-foreground">Full example content coming soon</p>
        <p className="mt-1 text-sm text-muted-foreground">
          Full narrative views, asset previews, and export samples will appear here once the product launches.
        </p>
      </div>
    </div>
  );
}
