import type { OnePagerRenderOutput } from "@/lib/renderers/types";
import { BASE_STYLES, ONE_PAGER_STYLES } from "./styles";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function generateOnePagerHtml(output: OnePagerRenderOutput): string {
  const { headline, sections, context } = output;

  const sectionsHtml = sections.map((s) => `
    <div class="section">
      <div class="section-header">
        <span class="section-title">${esc(s.title)}</span>
        <span class="tag tag-${s.confidence}">${s.confidence}</span>
      </div>
      <div class="section-body">${esc(s.content)}</div>
    </div>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(context.projectName)} &mdash; One-Pager v${context.versionNumber}</title>
  <style>${BASE_STYLES}${ONE_PAGER_STYLES}</style>
</head>
<body>
  <div class="doc">
    <h1 class="doc-headline">${esc(headline)}</h1>
    ${sectionsHtml}
    <footer class="doc-footer">
      <span>${esc(context.projectName)} &middot; One-Pager v${context.versionNumber}</span>
      <span>Generated by Go-to-Market Taste &middot; ${esc(context.generatedAt)}</span>
    </footer>
  </div>
</body>
</html>`;
}
