import type { PitchDeckRenderOutput } from "@/lib/renderers/types";
import { BASE_STYLES, PITCH_DECK_STYLES } from "./styles";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function generatePitchDeckHtml(output: PitchDeckRenderOutput): string {
  const { slides, context } = output;

  const slidesHtml = slides.map((s) => `
  <div class="slide">
    <span class="slide-num">${s.slideNumber} / ${slides.length}</span>
    <div class="slide-label">${esc(s.title)}</div>
    <div class="slide-body">${esc(s.content)}</div>
    <div class="slide-badge"><span class="tag tag-${s.confidence}">${s.confidence}</span></div>
  </div>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(context.projectName)} — Pitch Deck v${context.versionNumber}</title>
  <style>${BASE_STYLES}${PITCH_DECK_STYLES}</style>
</head>
<body>
  <div class="deck-header no-print">
    <h1>${esc(context.projectName)}</h1>
    <span class="meta">Pitch Deck &middot; v${context.versionNumber} &middot; ${esc(context.generatedAt)}</span>
  </div>
  <div class="slides">${slidesHtml}</div>
  <footer class="no-print" style="text-align:center;font-size:.65rem;color:#9ca3af;padding:2rem 0 3rem">
    Generated by Go-to-Market Taste &middot; asset version ${esc(context.assetVersionId.slice(0, 8))}
  </footer>
</body>
</html>`;
}
