import type { SalesDeckRenderOutput } from "@/lib/renderers/types";
import { BASE_STYLES, SALES_DECK_STYLES } from "./styles";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function generateSalesDeckHtml(output: SalesDeckRenderOutput): string {
  const { tabs, context } = output;

  const tocLinks = tabs.map((t) =>
    `<a class="toc-link" href="#${t.id}">${esc(t.label)}</a>`
  ).join("\n");

  const tabsHtml = tabs.map((t) => `
    <div class="tab-group" id="${t.id}">
      <h2 class="tab-title">${esc(t.label)}</h2>
      ${t.sections.map((s) => `
      <div class="section">
        <div class="section-header">
          <span class="section-title">${esc(s.title)}</span>
          <span class="tag tag-${s.confidence}">${s.confidence}</span>
        </div>
        <div class="section-body">${esc(s.content)}</div>
      </div>`).join("")}
    </div>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(context.projectName)} &mdash; Sales Enablement Deck v${context.versionNumber}</title>
  <style>${BASE_STYLES}${SALES_DECK_STYLES}</style>
</head>
<body>
  <div class="deck">
    <h1 class="deck-title">${esc(context.projectName)}</h1>
    <p class="deck-meta">Sales Enablement Deck &middot; v${context.versionNumber} &middot; ${esc(context.generatedAt)}</p>
    <div class="toc no-print">
      <div class="toc-label">Jump to section</div>
      <div class="toc-links">${tocLinks}</div>
    </div>
    ${tabsHtml}
    <footer style="font-size:.65rem;color:#9ca3af;padding:2rem 0 1rem;border-top:1px solid var(--border);margin-top:2rem">
      Generated by Go-to-Market Taste &middot; asset version ${esc(context.assetVersionId.slice(0, 8))}
    </footer>
  </div>
</body>
</html>`;
}
